
SHELL = /bin/sh

#
# Visual Assistant SHell, ASCII remix
# 2016 by Sergey Vovk
# GPL or MIT License on your taste
# 

# this is permanent, other value not tested yet.
# TODO: separate config files from binaries installed
#DEST  = /usr/local
DEST  = /usr

DESTDIR = /tmp

VISI  = visi
VISILIB = $(DESTDIR)$(DEST)/lib/visi

#SHOWCONFIG = showconfig
SHOWCONFIG =
MAKECONF   = ./conf/Makefile
BLDCFG	= ./BLD.conf

include $(BLDCFG)

#PATH	= $(TOPDIR)/visi/bin:$(PATH)

all:	compile bld

help:	info

info:;
	@echo	'Please, check and edit file '$(MAKECONF)', then'
	@echo	''
	@echo	'    make cfg		# TOPDIR setup, create '$(BLDCFG)' include file'
	@echo	'    make all		# compile all binaries from source files'
	@echo	'    make bld		# prepare binaries for packaging'
	@echo	' or'
	@echo	'    make install	# install binaries without packaging'
	@echo	'    make clean		# clean subproject directories'
	@echo	'    make cleandist	# cleanup distribution from garbage files'
	@echo	''
	$(MAKE)	SHOWCONFIG=yes yes

# TOPDIR must be overriden via BLDCFG generated by 'make bldcfg'
TOPDIR	= .

cfg:	$(BLDCFG)

configure: cfg

$(BLDCFG):
	echo '#' `date` > $@
	echo '' >> $@
	echo 'TOPDIR	= '`pwd` >> $@
	echo '' >> $@
	echo 'DEST	= /usr' >> $@
	echo '' >> $@
	echo 'PATH	= '`pwd`'/visi/bin:'$(PATH) >> $@
	echo '' >> $@

###include ./Make.conf
include $(MAKECONF)

BLD	= $(TOPDIR)/BLD

VHSET	= ./vhset
VASH	= ./vash
VASHLIB	= ./vashlib

#all:	compile

compile:    $(BLDCFG) $(VISI)/include/line.h vashlib/LIB-$(ASHLIB)
	cd $(VISI)/src;        $(MAKE) install "CFLAGS_VISI=$(CFLAGS_VISI)"\
		"CC=$(CC)" "LINKER=$(LINKER)"
	cd $(VHSET); $(MAKE) all "DEST=$(DEST)"
	cd $(VASH);   $(MAKE) all "DEST=$(DEST)" "CFLAGS_ASH=$(CFLAGS_ASH)"
	cd vashlib/LIB;           $(MAKE) "DEST=$(DEST)" all
	cd vashlib/LIB-$(ASHLIB); $(MAKE) "DEST=$(DEST)" all

install:   $(DESTDIR) $(DEST) termcap $(VISILIB)
	cd $(VHSET); $(MAKE) install CFLAGS_VISI="$(CFLAGS_VISI)" "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"
	cd $(VASH);  $(MAKE) install "CFLAGS_ASH=$(CFLAGS_ASH)" "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"
	cd vashlib/LIB;			$(MAKE) install "DEST=$(DEST)"  "DESTDIR=$(DESTDIR)"
	cd vashlib/LIB-$(ASHLIB);	$(MAKE) install "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"
	cp -rp termcap/. $(VISILIB)
	cd visilib;			$(MAKE) install "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"

bld:	pkgbuild

pkgbuild: all $(BLD)
	cd $(VHSET); $(MAKE) install CFLAGS_VISI="$(CFLAGS_VISI)" "DEST=$(BLD)"
	cd $(VASH);  $(MAKE) install "CFLAGS_ASH=$(CFLAGS_ASH)" "DEST=$(BLD)"
	cd vashlib/LIB;			$(MAKE) install "DEST=$(BLD)"
#	cd vashlib/LIB-$(ASHLIB);	$(MAKE) install "DEST=$(BLD)"
#	cd visilib;			$(MAKE) install "DEST=$(BLD)"

clean:
	cd $(VISI)/bin; rm -f *
	cd $(VISI)/lib; rm -f *
	cd $(VISI)/src; $(MAKE) clean
	cd $(VHSET); $(MAKE) clean
	cd $(VASH); $(MAKE) clean
	cd vashlib/LIB; $(MAKE) clean
	cd vashlib/LIB-$(ASHLIB); $(MAKE) clean

cleandist:	clean
	rm -rf $(BLDCFG) $(BLD)
	find . -name BLD -exec rm -rf '{}' ';'
	find . '('      -name core -o \
			-name '*.b' -o \
			-name '*~' -o \
			-name 'core.*' -o \
			-name '*.core' -o \
			-name a \
		')' -exec rm -f '{}' ';'

$(BLD):
	-mkdir -p $(BLD)
	test -d $(BLD)

$(DEST):
	-mkdir -p $(DEST)
	test -d $(DEST)

$(DESTDIR):
	-mkdir -p $(DESTDIR)
	test -d $(DESTDIR)

$(VISILIB):
	-mkdir -p $(VISILIB)
	test -d $(VISILIB)
