
SHELL = /bin/sh

#
# Visual Assistant Shell
# 1990-2020 (C) Sergey Vovk
#
# MIT License
# 

# this is permanent, other value not tested yet.
# TODO: separate config files from binaries installed
#DEST  = /usr/local
DEST  = /usr

TOPDIR = /tmp

MAKECONF   = ./conf/Makefile
BLDCFG	= conf.cfg

BLD	= $(TOPDIR)/BLD
#BLD	= .
DESTDIR	= $(TOPDIR)/BLD
VERSN	= "1."

include $(BLDCFG)
include $(MAKECONF)

###include ./Make.conf
#include $(MAKECONF)

VISI  = visi
VISILIB = $(DESTDIR)$(DEST)/lib/visi

#DESTDIR = $(TOPDIR)

VHSET	= ./vhset
VASH	= ./vash
VASHLIB	= ./vashlib

#PATH	= $(TOPDIR)/visi/bin:$(PATH)

all:
	$(MAKE) setup
	$(MAKE) visi_lib
	$(MAKE) compile

#all:	compile bld

#help:	info

#SHOWCONFIG = showconfig
SHOWCONFIG =

# TOPDIR must be overriden via BLDCFG generated by 'make bldcfg'
#TOPDIR	= .

help:
	@echo	'Please, check and edit file '$(MAKECONF)', then'
	@echo	''
	@echo	'    make cfg		# TOPDIR setup, create '$(BLDCFG)' include file'
	@echo	'    make all		# compile all binaries from source files'
	@echo	'    make bld		# prepare binaries for packaging'
	@echo	' or'
	@echo	'    make install	# install binaries without packaging'
	@echo	'    make clean		# clean subproject directories'
	@echo	'    make distclean	# cleanup distribution from garbage files'
	@echo	''
	$(MAKE)	showconfig
	#$(MAKE)	SHOWCONFIG=yes yes


setup:
	@set -x; if [ -s "$(BLDCFG)" ]; then true; else ./configure; fi   

#cfg:
#	./configure
#	$(MAKE) $(BLDCFG)

#$(SHOWCONFIG):
showconfig:
	@echo '***** Make.conf variables configured:'
	@echo PATH=$(PATH)
	@echo DEST=$(DEST)
	@echo DESTDIR=$(DESTDIR)
	@echo TOPDIR=$(TOPDIR)
	@echo PKGBLD=$(PKGBLD)
	@echo CC=$(CC)
	@echo LINKER=$(LINKER)
	@echo VISI=$(VISI)
	@echo CFLAGS_ASH=$(CFLAGS_ASH)
	@echo CFLAGS_VISI=$(CFLAGS_VISI)

visi_lib:; # $(BLDCFG) $(VISI)/include/line.h $(VISILIB_LIST)
	cd $(VISI)/src;        $(MAKE) install "CFLAGS_VISI=$(CFLAGS_VISI)"\
		"CC=$(CC)" "LINKER=$(LINKER)"

compile:   $(BLDCFG) $(VISI)/include/line.h vashlib/LIB-$(ASHLIB)
	cd $(VHSET); $(MAKE) all "DEST=$(DEST)"
	cd $(VASH);   $(MAKE) all "DEST=$(DEST)" "CFLAGS_ASH=$(CFLAGS_ASH)" \
		"VERSN=$(VERSN)"
	cd vashlib/LIB;           $(MAKE) "DEST=$(DEST)" all
#	cd vashlib/LIB-$(ASHLIB); $(MAKE) "DEST=$(DEST)" all

#install:   $(DESTDIR) $(DEST) termcap $(VISILIB)
install:   $(DESTDIR) $(DEST) $(VISILIB)
	cd $(VHSET); $(MAKE) install CFLAGS_VISI="$(CFLAGS_VISI)" "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"
	cd $(VASH);  $(MAKE) install "CFLAGS_ASH=$(CFLAGS_ASH)" "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"
	cd vashrc;	$(MAKE) install "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"
	cd vashbin;	$(MAKE) install "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"
	cd vashlib/LIB;			$(MAKE) install "DEST=$(DEST)"  "DESTDIR=$(DESTDIR)"
#	cd vashlib/LIB-$(ASHLIB);	$(MAKE) install "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"
#	cp -rp termcap/. $(VISILIB)
#	cd visilib;			$(MAKE) install "DEST=$(DEST)" "DESTDIR=$(DESTDIR)"

# vashrc contains nothing to be clean
clean:
	cd $(VISI)/bin; rm -f *
	cd $(VISI)/lib; rm -f *
	cd $(VISI)/src; $(MAKE) clean
	cd $(VHSET); $(MAKE) clean
	cd $(VASH); $(MAKE) clean
	cd vashlib/LIB; $(MAKE) clean
	cd vtest; $(MAKE) clean
	rm -f $(BLDCFG) 
	touch $(BLDCFG)
#	cd vashlib/LIB-$(ASHLIB); $(MAKE) clean

distclean:	clean
	find . -type f -a '(' \
			-name core -o \
			-name '*.b' -o \
			-name '*~' -o \
			-name 'core.*' -o \
			-name '*.core' -o \
			-name a \
		')' -exec rm -f '{}' ';'
	rm -rf $(BLD)

$(DEST):
	mkdir -p $(DEST)

$(DESTDIR):
	mkdir -p $(DESTDIR)

$(VISILIB):
	mkdir -p $(VISILIB)
