#!/bin/sh

if [ -x /usr/local/bin/less ]
then
	LESS=csb40; export LESS
	MOREPROG=/usr/local/bin/less
elif [ -x /usr/bin/more ]
then
	MOREPROG=/usr/bin/more
elif [ -x /usr/bin/pg ]
then
	MOREPROG=/usr/bin/pg
fi

exec ${MOREPROG} $@
