.TH LDEMO 1 LINLIB
.SH ИМЯ
ldemo, linlib \- ДЕМОНСТРАЦИОННАЯ ПРОГРАММА LINLIB
.SH
.ES
 +----------+   БИБЛИОТЕКА ВВОДА-ВЫВОДА
(c) linlib  !   ДЛЯ АЛФАВИТНО-ЦИФРОВЫХ
 +----------+   ВИДЕОТЕРМИНАЛОВ
.EE
.SH ФОРМАТ
 ldemo

.SH ОПИСАНИЕ
.PP
Эта команда является иллюстрацией к использованию инструментального
комплекса linlib.
.PP
В начале работы программы на экране изображено меню,
выбор осуществляется подводом курсора к началу требуемого поля
и нажатием клавиши "пробел".
.PP
Не хватит никакой бумаги, что-бы описывать подробно,
что делается в этой программе и почему так, а не иначе.
Как известно, Лучше один раз увидеть, поэтому
программа устроена таким образом,
чтобы свести к минимуму чтение всяческих руководств.
Все пояснения и их выдача по запросу
упрятаны в самой программе.
Программисту, кроме того, понадобятся листинги
текстов этой программы, которые должны быть
доступны в каталогах малого дистрибутива linlib.
.SH ПРИМЕРЫ
.SH ДОПОЛНИТЕЛЬНЫЕ ССЫЛКИ
linlib(3x), lin1(3x), lin2(3x), lin3(3x), lin4(3x),
ajobs(3x), termcap(5).
.SH ЗАМЕЧАНИЯ
Некоторая полезная информация для настройки ldemo
содержится в каталоге малого дистрибутива.
