#!/bin/sh
#
# Assistant for sh startup
# Version for SVR4.x
#------------------------------
# First Bourne' shell started,
# then exec setup environ, then exec ash
#------------------------------
#
# DEBUG switch: uncomment next line.
# set -x

# hardcoded in termcap/termnew as default
#TERMCAP=/usr/local/etc/termcap
#export TERMCAP

# hack to proper working old 8-byte encoding
#export LC_ALL=
#export LANG=en_US.ISO8859-1
#export LC_CTYPE=ru_RU.KOI8-R
#export LC_COLLATE=$LC_CTYPE

#echo '
#	To use on-line help type ? or HELP metakey
#'

#
#---------------------------------------------
# environ-passed setup (VASH):
#
# h     history will be stored
# lNN   lines for filename menu (from 2 to 20), default 10
# p     key help panel bar on
# s     scroll cmd script but no clear screen
# c     clock show,  uprigh corner of screen
# m     check mailbox (Biff)
#
# example for assist environ-passed setup:

#VASH=l10pshcm
VASH=

#---------------------------------------------
# label for identification machine name, /dev/tty???,
# and other likely info.
# ASHLBL
#
case l"$LOGNAME" in
l)      case u"$USER" in
	u)      user=''
		;;
	u*)     user="$USER"
		;;
	esac
	;;
l*)     user="$LOGNAME"
	;;
esac

ttyfull=`tty`
#tty=`basename $ttyfull`
tty=`echo $ttyfull|sed -e 's-/dev/--'`
uname=`uname -n || hostname | sed -e 's/\..$*//' 2>/dev/null`
#ASHLBL=' '"$user@$uname $tty"' '
#
# 
# hint: if last sybol in ASHLBL is ':' (colon), vash append current working directory
# since vash-1.26.4
ASHLBL="$tty $user@$uname:"
#"$user"' '

# .ashstd: #e - EDITOR, #m - PAGER
#EDITOR=vi
#PAGER=/usr/local/bin/m
PAGER=less

export ASHLBL PATH
#export EDITOR PAGER
export PAGER

#stty kill '^u'

PS1='v> '; export PS1

VASH=l10shw

# decoration on xterm window
onxterm=0
if [ x$DISPLAY != x ]; then
    onxterm=1
fi
case $TERM in
xterm*|vs100*|iris-*)
    onxterm=1;;
screen*|tmux*)
    onxterm=0;;
esac
if [ 1 -eq $onxterm ]; then
	# reset PS1 
	# now compiled into vash binary:
	#echo ']0;'"$ASHLBL"''
	#eval `/usr/bin/X11/resize -u`
	#eval `/usr/bin/resize -u`
	#export TERMCAP
	VASH=px$VASH
else
    VASH=p$VASH
fi
# append clock on hardware console screen
case $TERM in
console|linux|pc*|vs100*|AT386)
	VASH=c$VASH
esac

export VASH
#debug: 
#VASH_VEXDIR=$HOME/proj-ws/remix/vashlib/LIB
export VASH_VEXDIR
env|grep VASH

exec vash "$@"
